Add views
dlwub/Rails-blog pull request #7
Opened 2023-04-06 15:35 UTC by dlwub

In this activity:
- Views have been added for index and show actions of the controllers

2023-04-06 16:41 UTC, VICTOR-CHUKWU requested changes
Hi @dlwub  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 16:41 UTC, VICTOR-CHUKWU commented on app/views/users/index.html.erb
> +    </ul>
- [ ] kindly make sure your user index page matches the given wireframe
your design :point_down: 
![Screenshot from 2023-04-06 17-29-46](https://user-images.githubusercontent.com/66097371/230440769-1ceaf543-ba52-49c0-864b-6862eb05e357.png)
wireframe :point_down: 
![Screenshot from 2023-04-06 17-30-29](https://user-images.githubusercontent.com/66097371/230440831-eca188e1-34b6-42b2-bed2-ffd74bf85c46.png)

2023-04-06 16:41 UTC, VICTOR-CHUKWU commented on app/views/users/show.html.erb
> +
- [ ] also kindy make your user show page to match the given wireframe
your design :point_down: 
![Screenshot from 2023-04-06 17-32-53](https://user-images.githubusercontent.com/66097371/230441220-3f1a5008-dc27-44ad-9245-546cc2d0ec64.png)
wireframe :point_down: 
![Screenshot from 2023-04-06 17-33-25](https://user-images.githubusercontent.com/66097371/230441277-313c029e-76fb-4f83-afaf-74ac26ed7d7a.png)

2023-04-06 16:41 UTC, VICTOR-CHUKWU commented on app/views/posts/index.html.erb
> +  <button class="post-btn">Pagination</button>
- [ ] kindly make your post index to match the wireframe too
your design :point_down: 
![Screenshot from 2023-04-06 17-36-16](https://user-images.githubusercontent.com/66097371/230441912-d25f4058-abd4-450f-82e2-fb1c80575942.png)

wireframe :point_down: 
![Screenshot from 2023-04-06 17-35-52](https://user-images.githubusercontent.com/66097371/230441987-7d1944d4-a58e-4e08-8f44-35d5d5ab36f3.png)

2023-04-06 16:41 UTC, VICTOR-CHUKWU commented on app/views/posts/show.html.erb
> +    </ul>
- [ ] your post show page should match the wire frame kindly fix this
your design :point_down: 
![Screenshot from 2023-04-06 17-39-18](https://user-images.githubusercontent.com/66097371/230442420-081412a9-7984-44e8-9580-af0f460f34b9.png)
wireframe :point_down: 
![Screenshot from 2023-04-06 17-38-50](https://user-images.githubusercontent.com/66097371/230442484-1f452294-6a4a-48e7-9a18-6b5d4f26f4dd.png)

2023-04-07 17:05 UTC, sumairq approved these changes
### Hi @dlwub , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 17:12 UTC, merged